export enum Environment {
  DEVELOPMENT = 'development',
  STAGING = 'staging',
  PRODUCTION = 'production',
}

export enum Econfig {
  ENVIRONMENT = 'ENVIRONMENT',

  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_DATABASE = 'POSTGRES_DATABASE',

  REDIS_URL = 'REDIS_URL',

  THROTTLE_LIMIT = 'THROTTLE_LIMIT',
  THROTTLE_TTL = 'THROTTLE_TTL',

  CLOUDINARY_API_KEY = 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET = 'CLOUDINARY_API_SECRET',
  CLOUD_NAME = 'CLOUD_NAME',

  KICK_BOX_API_KEY = 'KICK_BOX_API_KEY',

  NODE_MAILER_USER = 'NODE_MAILER_USER',
  NODE_MAILER_PASS = 'NODE_MAILER_PASS',

  BYPASS_EMAIL_EXISTENCE_CHECK = 'BYPASS_EMAIL_EXISTENCE_CHECK',
}

export type TConfig = `${Econfig}`;

export enum Folders {
  BASE_PATH = 'instagram-clone-be',
  PRIFILE_PIC = 'profile-pic',
}

export enum FileTypes {
  IMAGE = 'image',
}
